"""Editorial write layer: identities, sessions, workflow metadata, lint runs (ADR-0010).

The public read model does not change: entities keep ``status`` and ``revision`` as the single
source of truth for *where* a record is in the review loop. What this migration adds is the
machinery that makes a write trustworthy:

* ``app_user.password_hash`` + ``app_session`` -- argon2id credentials and opaque session tokens
  (the table stores only the SHA-256 digest of the cookie value, never the cookie itself).
* ``editorial_state`` -- who submitted / reviewed / published / archived, when, and with what
  note, plus ``head_id``, the link that implements the reviewed-copy pattern: editing a published
  entity creates a draft row whose ``head_id`` points at the live record, so the public version is
  never half-edited.
* ``lint_run`` -- every data-lint report, so "we checked" is a fact with a timestamp (docs/07 §3).
* CHECK constraints on the vocabularies, because a typo in a status must fail at the database, not
  silently disappear from a filter.

Revision ID: 0003_editorial_write_layer
Revises: 0002_search_normalisation
Create Date: 2026-09-13
"""

from __future__ import annotations

from alembic import op

revision = "0003_editorial_write_layer"
down_revision = "0002_search_normalisation"
branch_labels = None
depends_on = None

ENTITY_TABLES = ("place", "person", "event", "political_entity", "article")

#: The editorial vocabulary. Kept in one place because it is used by CHECK constraints on eight
#: tables and must match ``azir.domain.enums.Status`` exactly (tests/test_postgis_schema.py).
STATUSES = ("draft", "in_review", "changes_requested", "published", "archived", "imported_unverified")
ROLES = ("admin", "reviewer", "editor", "contributor")
ASSERTION_STATUSES = ("proposed", "accepted", "rejected", "disputed")


def _in_list(values: tuple[str, ...]) -> str:
    return ", ".join(f"'{value}'" for value in values)


IDENTITY = f"""
ALTER TABLE public.app_user ADD COLUMN password_hash TEXT;
ALTER TABLE public.app_user ADD COLUMN last_login_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.app_user
    ADD CONSTRAINT ck_app_user_role CHECK (role IN ({_in_list(ROLES)}));

CREATE TABLE public.app_session (
	id TEXT NOT NULL,
	user_id TEXT NOT NULL,
	csrf_hash TEXT NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
	revoked_at TIMESTAMP WITH TIME ZONE,
	user_agent TEXT,
	CONSTRAINT pk_app_session PRIMARY KEY (id),
	CONSTRAINT fk_app_session_user_id_app_user FOREIGN KEY(user_id) REFERENCES public.app_user (id) ON DELETE CASCADE
);

CREATE INDEX ix_app_session_user ON public.app_session (user_id, expires_at DESC);
CREATE INDEX ix_app_session_expires ON public.app_session (expires_at);
"""

WORKFLOW = f"""
CREATE TABLE public.editorial_state (
	entity_type TEXT NOT NULL,
	entity_id TEXT NOT NULL,
	revision INTEGER DEFAULT '1' NOT NULL,
	head_id TEXT,
	submitted_by TEXT,
	submitted_at TIMESTAMP WITH TIME ZONE,
	reviewed_by TEXT,
	reviewed_at TIMESTAMP WITH TIME ZONE,
	review_note TEXT,
	published_by TEXT,
	published_at TIMESTAMP WITH TIME ZONE,
	archived_by TEXT,
	archived_at TIMESTAMP WITH TIME ZONE,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	CONSTRAINT pk_editorial_state PRIMARY KEY (entity_type, entity_id),
	CONSTRAINT fk_editorial_state_submitted_by_app_user FOREIGN KEY(submitted_by) REFERENCES public.app_user (id),
	CONSTRAINT fk_editorial_state_reviewed_by_app_user FOREIGN KEY(reviewed_by) REFERENCES public.app_user (id),
	CONSTRAINT fk_editorial_state_published_by_app_user FOREIGN KEY(published_by) REFERENCES public.app_user (id),
	CONSTRAINT fk_editorial_state_archived_by_app_user FOREIGN KEY(archived_by) REFERENCES public.app_user (id)
);

CREATE INDEX ix_editorial_state_head ON public.editorial_state (head_id, entity_type);
CREATE INDEX ix_editorial_state_updated ON public.editorial_state (updated_at DESC);
"""

LINT = """
CREATE TABLE public.lint_run (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	scope TEXT DEFAULT 'corpus' NOT NULL,
	actor_id TEXT,
	errors INTEGER DEFAULT '0' NOT NULL,
	warnings INTEGER DEFAULT '0' NOT NULL,
	findings JSONB DEFAULT '[]' NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
	CONSTRAINT pk_lint_run PRIMARY KEY (id),
	CONSTRAINT fk_lint_run_actor_id_app_user FOREIGN KEY(actor_id) REFERENCES public.app_user (id)
);

CREATE INDEX ix_lint_run_created ON public.lint_run (created_at DESC);
"""

CONSTRAINTS = f"""
ALTER TABLE public.assertion ADD COLUMN reviewed_by TEXT;
ALTER TABLE public.assertion ADD COLUMN reviewed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.assertion ADD COLUMN review_note TEXT;
ALTER TABLE public.assertion
    ADD CONSTRAINT ck_assertion_status CHECK (status IN ({_in_list(ASSERTION_STATUSES)}));
ALTER TABLE public.source
    ADD CONSTRAINT ck_source_status CHECK (status IN ({_in_list(STATUSES)}));
ALTER TABLE public.period
    ADD CONSTRAINT ck_period_status CHECK (status IN ({_in_list(STATUSES)}));
""" + "".join(
    f"""
ALTER TABLE public.{table}
    ADD CONSTRAINT ck_{table}_status CHECK (status IN ({_in_list(STATUSES)}));
ALTER TABLE public.{table}
    ADD CONSTRAINT ck_{table}_revision CHECK (revision >= 1);"""
    for table in ENTITY_TABLES
)

TRIGGERS = """
CREATE FUNCTION public.azir_touch_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $fn$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$fn$;
""" + "".join(
    f"""
CREATE TRIGGER trg_{table}_updated
    BEFORE UPDATE ON public.{table}
    FOR EACH ROW EXECUTE FUNCTION public.azir_touch_updated_at();"""
    for table in (*ENTITY_TABLES, "editorial_state")
)


def upgrade() -> None:
    for statement in (IDENTITY, WORKFLOW, LINT, CONSTRAINTS, TRIGGERS):
        op.execute(statement)


def downgrade() -> None:
    for table in (*ENTITY_TABLES, "editorial_state"):
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_updated ON public.{table};")
    op.execute("DROP FUNCTION IF EXISTS public.azir_touch_updated_at();")
    for table in ENTITY_TABLES:
        op.execute(f"ALTER TABLE public.{table} DROP CONSTRAINT IF EXISTS ck_{table}_revision;")
        op.execute(f"ALTER TABLE public.{table} DROP CONSTRAINT IF EXISTS ck_{table}_status;")
    op.execute("ALTER TABLE public.period DROP CONSTRAINT IF EXISTS ck_period_status;")
    op.execute("ALTER TABLE public.source DROP CONSTRAINT IF EXISTS ck_source_status;")
    op.execute("ALTER TABLE public.assertion DROP CONSTRAINT IF EXISTS ck_assertion_status;")
    for column in ("review_note", "reviewed_at", "reviewed_by"):
        op.execute(f"ALTER TABLE public.assertion DROP COLUMN IF EXISTS {column};")
    for table in ("lint_run", "editorial_state", "app_session"):
        op.execute(f"DROP TABLE IF EXISTS public.{table} CASCADE;")
    op.execute("ALTER TABLE public.app_user DROP CONSTRAINT IF EXISTS ck_app_user_role;")
    for column in ("last_login_at", "password_hash"):
        op.execute(f"ALTER TABLE public.app_user DROP COLUMN IF EXISTS {column};")
